### ISSUE TITLE
IllegalStateException in PcmBeagleMappings#addPcmIdOf

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#770]
An injection Exception caused by a IllegalStateException is thrown when trying to Analyse CocoMe with Beagle.

```
Caused by: java.lang.IllegalStateException
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmBeagleMappings.addPcmIdOf(PcmBeagleMappings.java:192)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.addInternalActionToSet(PcmRepositorySeffExtractor.java:186)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:119)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBranchAction(PcmRepositorySeffExtractor.java:163)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:124)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBranchAction(PcmRepositorySeffExtractor.java:163)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:124)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBranchAction(PcmRepositorySeffExtractor.java:163)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:124)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBranchAction(PcmRepositorySeffExtractor.java:163)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:124)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositoryExtractor.extractResourceDemandingSEFFImplAndAddContentsToSet(PcmRepositoryExtractor.java:237)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositoryExtractor.extractBasicComponentAndAddContentsToSet(PcmRepositoryExtractor.java:223)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositoryExtractor.scanRepository(PcmRepositoryExtractor.java:207)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositoryExtractor.getBlackboardForAllElements(PcmRepositoryExtractor.java:100)
```

> Ja, die IllegalStateException wird geworfen, weil Somox unterschiedliche Seff Elemente auf die gleiche CodeSections mappt (zumindest das was in den EntityNames steht, aus denen ich parse)

> Wenn wir das SourceCode Mapping mit dem Decorator hinbekommen, sollte das Problem gefixt sein. Andernfalls muss es auskommentiert werden oder Somox überarbeitet werden.

**Comment by jGleitz** [comment]
It seems like this exception is thrown for any bigger repository. Thus, we need to deal with it.

Having multiple IDs for the same thing is horrible. However, I don’t think we can fix that because it’s a bug in SoMoX.

Making our code worse because other code is bad is horrible, too. But this exception keeps us from evaluating our project, which is not acceptable. So please remove the check throwing the exception asap.
